### ISSUE TITLE
Will this process work on linux/ubuntu as well?

### ISSUE THREAD

**Issue by pratikkaushik14** [altova/SECDB#13]
Hello there! I tried the whole process in my ubuntu system by installing altova raptor and license server of linux. Afterwards my feed_tools.py is running successfully on my linux system but when I  run download_feeds.py it shows many errors.

I am posting them as below ---->
root@ubuntu-s-1vcpu-1gb-nyc1-01:/opt/Altova/RaptorXMLXBRLServer2020/bin# ./raptorxmlxbrl-python Scripts/download_feeds.py
2020-01-16 12:43:09,601 INFO Downloading RSS feed http://www.sec.gov/Archives/edgar/monthly/xbrlrss-2005-04.xml
Traceback (most recent call last):
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Scripts/download_feeds.py", line 99, in <module>
    main()
  File "Scripts/download_feeds.py", line 95, in main
    download_feeds(args)
  File "Scripts/download_feeds.py", line 63, in download_feeds
    feeds.append(download_feed(feed))
  File "Scripts/download_feeds.py", line 30, in download_feed
    filepath = feed.download(feed_dir)
  File "/opt/Altova/RaptorXMLXBRLServer2020/bin/Scripts/feed_tools.py", line 93, in download
    urllib.request.urlretrieve(self.url,filepath)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/Altova/RaptorXMLXBRLServer2020/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)>

-------------------------------------------------------------------------------------------------------------
Can you please help me with the same?
Thank you

**Comment by xmldev** [comment]
works on linux too, we had to fix the certificate handling.
thanks for reporting :)

**Comment by pratikkaushik14** [comment]
Thanks for your response.
Although SSL certificate error still persists, can you tell me how can I resolve it??
Those errors which I have reported to you still exist even when I installed SSL certificate on my linux server.

Please tell me how can I solve it.
Thank you

**Comment by xmldev** [comment]
hi pratikkaushik14! you shouldn't need to install any SSL certificate to get this script running; we tested the modifications on ubuntu 19.10 with python 3.7.2 ; i've reopened the issue, could you please send us the backtrace that you get with the latest version of the script? thx

**Comment by pratikkaushik14** [comment]
Hello there!, I'm glad to receive responses from your end. I have successfully implemented the whole SECDB process and got the SEC filings data as well. Although, the database file which is generated at the end of the process which contains all the tables of data is in SQLite format. 

However, I am working on Oracle Power BI and need the database generated file which is supported by Oracle but I am not able to generate the same.

Can you please help me in this?
Thank you

**Comment by afalk42** [comment]
I'm afraid you will need to rewrite the Python scripts yourself - and modify all the database calls - if you want to target another database server platform...

**Comment by pratikkaushik14** [comment]
I'm thankful for your responses.
I have completed the setup to pull data from the website and in the end, one database file is generated which is for SQLite Database.

In addition, I have tried exporting the same database file into .SQL format or .db format whichever is acceptable by Oracle database. Although, Oracle database is unable to import the same file which iI have exported from SQLite database.
Even I performed the same procedure and tried to import the exported file into MySQL Database and that also failed.
-----------------------------------------------------------------------------------------------------------
Can you please tell me why this is happening, as I don't want to re-write the python scripts.
If the SQLite database is generated then why it can't be used in oracle database even after exporting the same file into the format acceptable by Oracle Database
![image](https://user-images.githubusercontent.com/34815826/75132249-3d650780-56fc-11ea-8124-2b557d91c749.png)

Please let me know, how can I solve this problem.

Thank you

**Comment by afalk42** [comment]
SQL dialects are not directly compatible between most database platforms. It is never as easy as exporting a .sql script from one database server and then executing that on another. If you Google for results on how to conver from SQLite to Oracle, you will see many different approaches. But it's not a simple process.

**Comment by pratikkaushik14** [comment]
Thanks a lot for your responses,

Can you tell me that this whole procedure will work without using Altova RaptorXMLXBRL Server?

As my trial has expired and the tool is really expensive for me.

Please tell me any alternate option so that I can run all the scripts replacing altova raptor.

Thank you

**Comment by afalk42** [comment]
No, this process will not work without Altova RaptorXML+XBRL Server. 

This is a demonstration project on how to utilize Altova RaptorXML+XBRL Server to process SEC filings and extract financial data from them into a SQL database. The functionality of the Altova RaptorXML+XBRL Server is essential to this project because Altova RaptorXML+XBRL Server does all the XBRL parsing and processing!!!

**Comment by pratikkaushik14** [comment]
Hello, thanks for your quick responses.

I cannot use Altova  RaptorXML+XBRL Server as it is expensive and it provides the license for only 30 days which is not enough for me. I am trying to process XBRL files and retrieve data to feed into the database.
I saw python-xbrl modules, GAAP-Serializer, XBRL and many other python modules all of them useless to process these XBRL filings.

Actually I am making a college project. Although, I am stuck in a position where you can help me in this. 
I have downloaded feeds and filings without using Altova RaptorXML+XBRL Server but when I try to feed them into the database, I can't proceed further. I went through many tutorials available online, but none of them was satisfactory and most of them are using Altova RaptorXML+XBRL Server.

Can you please help me in this and let me know if there is any possible way that I can do this complete project without using Altova RaptorXML+XBRL Server??

Thank you

**Comment by afalk42** [comment]
Sorry, but you are looking at an example project of how to process SEC data using Altova RaptorXML+XBRL Server. If you don't want to use our software, you should look elsewhere...
