### ISSUE TITLE
ContentTooShortError

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#8]
I'm getting this in my download_filings.py:
Traceback (most recent call last):
  File "scripts\download_filings.py", line 113, in <module>
    main()
  File "scripts\download_filings.py", line 109, in main
    download_filings(feedpath,args)
  File "scripts\download_filings.py", line 68, in download_filings
    download_filing(dir,url)
  File "scripts\download_filings.py", line 36, in download_filing
    urllib.request.urlretrieve(url,filepath)
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 219, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 17832 out of 341517 bytes>

**Comment by afalk42** [comment]
Those issues seem to be most likely caused by a poor internet connection. For example, the Python documentation states that:

> urlretrieve() will raise ContentTooShortError when it detects that the amount of data available was less than the expected amount (which is the size reported by a Content-Length header). This can occur, for example, when the download is interrupted.

To alleviated this, we have uploaded a new version of the download_filings.py script which now also supports a --retries option. It is set by default to 3 but in this case I would advise to set it explicitly to a higher number. I’m not sure if there is anything else we can do, as this is an Internet connectivity question between your location and the SEC servers in the US.
