### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by ahmedmohiduet** [altova/SECDB#9]
I'm getting this error in my download_filings.py:
Traceback (most recent call last):
  File "scripts\download_filings.py", line 113, in <module>
    main()
  File "scripts\download_filings.py", line 109, in main
    download_filings(feedpath,args)
  File "scripts\download_filings.py", line 68, in download_filings
    download_filing(dir,url)
  File "scripts\download_filings.py", line 36, in download_filing
    urllib.request.urlretrieve(url,filepath)
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 178, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 1202, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files (x86)\Altova\RaptorXMLXBRLServer2016\lib\python3.4\lib\urllib\request.py", line 1176, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly re
spond after a period of time, or established connection failed because connected host has failed to respond>

Any ideas?

**Comment by afalk42** [comment]
See our response to issue #8 - this is due to Internet connectivity issues between your location and the SEC servers in the US. Try increasing the --retries parameter to see if that solves it.
